module.exports = {
  ClientEnum: {
    ADMIN_TYPE: "ADMIN",
    STUDENT_TYPE: "STUDENT",
    TEACHER_TYPE: "TEACHER",
    RESPONSE_CONNECTION_ERROR: "Database Connection Failed",

    SUPERINDENDENT_TYPE: "SUPERINTENDENT",
    IN_OUT_CLERK: "IN OUT CLERK",
    ACCEPTANCE_CLERK: "ACCEPTANCE CLERK",
  },
};
